version: '3'
services:
  client-react:
    build: .
    image: mubbaseer/chatapp-client-react
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - REACT_APP_CHAT_ENGINE_PROJECT_ID=04b533d6-d05a-4825-9d4a-ca32b8bb35a4
    ports:
      - 3000:80