version: '3'
services:
  server-nodejs:
    build: .
    image: mubbaseer/chatapp-server-nodejs
    environment:
      - NODE_PORT=3001
      - CHAT_ENGINE_PROJECT_ID=98496bbc-176c-49b0-98dc-1d6d44334e0c
      - CHAT_ENGINE_PRIVATE_KEY=444a3eb9-fed6-46a0-a055-e04a441d4b0a
    ports:
      - 3001:3001