version: '3'
services:
  server-nodejs:
    build: .
    image: mubbaseer/chatapp-server-nodejs
    environment:
      - NODE_PORT=3001
      - CHAT_ENGINE_PROJECT_ID=04b533d6-d05a-4825-9d4a-ca32b8bb35a4
      - CHAT_ENGINE_PRIVATE_KEY=ea660016-5b3b-4603-9667-64f31f2eadd4
    ports:
      - 3001:3001