# name: Workflow Name
# on:
#   event_name:
#     # Event triggers here
# jobs:
#   job_name:
#     runs-on: ubuntu-latest  # The virtual environment where the job runs
#     steps:
#       - name: Step 1
#         # Action for step 1
#       - name: Step 2
#         # Action for step 2

name: Build and Test
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: npm install
        working-directory: ./server-nodejs

      # - name: run
      #   run: node index.js
      #   working-directory: ./server-nodejs
